name: Sync Fork

on:
  schedule:
    - cron: '0 2 * * *'   # 每天凌晨2点自动运行（UTC时间，要换成北京时间+8）
  workflow_dispatch:       # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/langgenius/dify.git
          git fetch upstream
          git checkout main
          git merge upstream/main || true
          git push origin main
