name: Sync All Branches and Tags

on:
  schedule:
    - cron: '0 2 * * *'   # 每天凌晨2点 UTC
  workflow_dispatch:       # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # 拉取所有历史记录
          persist-credentials: false

      - name: Set Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch all branches and tags
        run: |
          git remote add upstream https://github.com/原作者/仓库名.git
          git fetch upstream --prune --tags
          
      - name: Sync branches
        run: |
          for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/upstream/); do
            git checkout ${branch#upstream/} 2>/dev/null || git checkout -b ${branch#upstream/} $branch
            git merge --ff-only $branch || echo "Branch ${branch#upstream/} already up-to-date"
            git push origin ${branch#upstream/}
          done

      - name: Push tags
        run: |
          git push --tags
